name: "SolarSynk"
description: "Home Assistant add-on for syncing solar/inverter data from SynSynk.net"
version: "2.1.3"
slug: "solar_synk"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  sunsynk_user: ""
  sunsynk_pass: ""
  sunsynk_serial: ""
  Home_Assistant_IP: ""
  Home_Assistant_PORT: 8123
  HA_LongLiveToken: ""
  Refresh_rate: 300
  
schema:
  sunsynk_user: str
  sunsynk_pass: str
  sunsynk_serial: str
  Home_Assistant_IP: str
  Home_Assistant_IP: int
  HA_LongLiveToken: str
  Refresh_rate: int
  
  
  

